import { ProjectProps } from "./types";

export const LABELSPROJECTS: ProjectProps[] = [
    {
        id: "micro-saas-todo",
        title: "Micro-saas Todo",
        gitUrl: "https://github.com/Hundlee/micro-saas-todo-app",
        deployURL: "https://micro-saas-todo-app-eosin.vercel.app/",
        image: "/micro-saas-todo.png",
        alt: "micro-saas-todo",
        description:
            "Um micro SaaS para gestão de tarefas, onde você pode criar e organizar suas tarefas diárias de forma eficiente. Ideal para otimizar seu tempo e aumentar sua produtividade.",
        technologies: [
            "typescript",
            "react",
            "nextJs",
            "tailwindCss",
            "prisma",
        ],
    },
    {
        id: "BarberShop",
        title: "BarberShop",
        gitUrl: "https://github.com/Hundlee/barberShop",
        deployURL: "https://barber-shop-bice.vercel.app/",
        image: "/barbershop.png",
        alt: "BarberShop",
        description: "App para marcar horários em barbearias cadastradas",
        technologies: [
            "typescript",
            "react",
            "nextJs",
            "tailwindCss",
            "prisma",
        ],
    },
    {
        id: "Portfólio",
        title: "Portfólio",
        gitUrl: "https://github.com/Hundlee/portfolio",
        image: "/portifolioProject.png",
        alt: "Portfólio",
        description: "Portfólio",
        technologies: ["typescript", "react", "nextJs", "tailwindCss"],
    },
    {
        id: "dailyExpend",
        title: "DailyExpend",
        gitUrl: "https://github.com/Hundlee/daily-expend",
        image: "/dailyExpend.png",
        deployURL: "https://daily-expend.vercel.app/",
        alt: "dailyExpend",
        description:
            "Um aplicativo para gerenciar seus gastos. Nele, você pode registrar suas despesas a data ficará salva, e ainda ter a flexibilidade de editar as informações posteriormente. Ideal para manter suas finanças organizadas e sob controle.",
        technologies: [
            "typescript",
            "react",
            "nextJs",
            "tailwindCss",
            "prisma",
        ],
    },
    {
        id: "ChatReact",
        title: "ChatReact",
        image: "/chatReact.png",
        gitUrl: "https://github.com/Hundlee/chatReact",
        deployURL: "https://chat-react-kohl.vercel.app/",
        alt: "ChatReact",
        description: "Chat criado com ReactJs e com Firebase",
        technologies: ["javascript", "react", "firebase", "sass"],
    },
    {
        id: "Chat Clinica",
        title: "Chat Clinica",
        image: "/clinicaChat.png",
        gitUrl: "https://github.com/Hundlee/chatClinica",
        deployURL: "https://chat-clinica.vercel.app/",
        alt: "Chat Clinica",
        description: "Chat para atendimento de uma clinica",
        technologies: ["react", "javascript", "html", "css", "firebase"],
    },
    {
        id: "ChatReact",
        title: "Conversor de Moedas",
        image: "/converterApp.png",
        gitUrl: "https://github.com/Hundlee/CorverterApp",
        deployURL: "https://corverter-app.vercel.app/",
        alt: "ChatReact",
        description: "Converte o preços das moedas selecionadas",
        technologies: ["javascript", "html", "css"],
    },
    {
        title: "Gerador de Senha",
        image: "/passwordGenerator.png",
        gitUrl: "https://github.com/Hundlee/Random-Password-Generator",
        deployURL: "https://random-password-generator-gamma-nine.vercel.app/",
        id: "Gerador de Senha",
        alt: "Gerador de Senha",
        description: "Gera senhas criptografadas",
        technologies: ["javascript", "html", "css"],
    },
    {
        id: "forlife",
        title: "FORLIFE",
        image: "/forLIFE.png",
        gitUrl: "https://github.com/Hundlee/site-responsivo-saude",
        deployURL: "https://site-responsivo-saude.vercel.app/",
        alt: "forlife",
        description: "landing page, site de saúde",
        technologies: ["javascript", "html", "sass", "css"],
    },
    {
        id: "snakeGame",
        title: "Snake game",
        image: "/snakegamee.png",
        gitUrl: "https://github.com/Hundlee/snakegame",
        deployURL: "https://snakegame-opal.vercel.app/",
        alt: "snakeGame",
        description: "Jogo da cobra feito com JS",
        technologies: ["javascript", "html", "css"],
    },
    {
        id: "Gerenciar usuarios",
        title: "Gerenciar usuários",
        image: "/backend.png",
        gitUrl: "https://github.com/Hundlee/users-manage-backend",
        alt: "Gerenciar usuarios",
        description: "Criar usuário | Backend",
        technologies: ["typescript", "nodejs", "prisma", "mongodb", "fastify"],
    },
    {
        id: "BotTelegram",
        title: "Bot Telegram Crypto",
        image: "/backend.png",
        gitUrl: "https://github.com/Hundlee/bot-telegram-crypto",
        alt: "BotTelegram",
        description: "Monitor valores de Cryptomoedas",
        technologies: ["typescript", "nodejs", "grammyY"],
    },
    {
        id: "contextAPI",
        title: "ContextAPI",
        image: "/contextAPI.png",
        gitUrl: "https://github.com/Hundlee/reactContextAPI",
        deployURL: "https://react-context-api-kappa.vercel.app",
        alt: "contextAPI",
        description: "Criar dados, usando context API",
        technologies: ["typescript", "react", "css"],
    },
];
